name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build executable with PyInstaller
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile main.py
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: dist/main

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: application
    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: release-application
        path: dist/main
